### ISSUE TITLE
SailsEmber.policies.emberSetHeader is not a constructor

### ISSUE THREAD

**Issue by EdsonJrMattos** [mdconaway/sails-ember-rest#10]
https://github.com/mdconaway/sails-ember-rest/blob/8819013f8014056492bf7a8a6489da35c843a730/templates/policies/emberSetHeader.js#L1

When i did run the code `  sails generate ember-rest policies `  on Sails.js,
It did returns me
```
error: A hook (policies) failed to load!
error: Failed to lift app: { Error: Attempted to require(D:\projetos\monitor-api\api\policies\emberSetHeader.js)  , but an error occurred: 

TypeError: SailsEmber.policies.emberSetHeader is not a constructor
    at Object.<anonymous> (D:\projetos\monitor-api\api\policies\emberSetHeader.js:2:18)

```
The solution that i found was modify the archive ` ./templates/policies/emberSetHeader ` adding  the contructor : 
```

const EmberController = require('./../controllers/EmberController');
module.exports = function(controller) {
  controller = controller ? controller : new EmberController();
  return function(req, res, next) {
    if (!req.headers.ember) {
        req.headers.ember = true;
    }
    next();
  };
};
```

**Comment by mdconaway** [comment]
Hmm, this looks like something related to arrow functions and how they relate to the `new` operator.

Technically this policy doesn't need to know about the ember controller, as it is purely a decorative policy for the incoming request.

I'll look into converting that file to export a classical function instead of an arrow function.  May have to revise the `prettier` rules if it is optimizing this file into an arrow function.

**Comment by mdconaway** [comment]
Hey I added a commit that should fix this. Publishing as 1.0.15.
