### ISSUE TITLE
Actions 2 support

### ISSUE THREAD

**Issue by erzzo** [mdconaway/sails-ember-rest#5]
Thanks for this library!
When I wanted to use the recommended [actions2](https://next.sailsjs.com/documentation/concepts/actions-and-controllers)
I've get an error: `The action find in someController/find.js conflicts with a previously-loaded action.`

Can I somehow work this around?
Thank you

**Comment by mdconaway** [comment]
Hey errzo!

Thanks for opening this. I'm currently on vacation but I will look at actions 2 support on Sunday and see if there is a way to resolve your problem. 

If you import your action in the controller js file and bind it directly to find in the controller declaration, does this alleviate the issue?

**Comment by mdconaway** [comment]
So I did some tinkering over the last couple of days, and I think I have a pretty good solution that will enable actions2 support based on what you have described above.

I added a new export grouping to the library (actions, or Actions), and it exports each sails-ember-rest action under its own constructor.  You can then build a hybrid custom controller using the action constructors as in the example/test server here: https://github.com/mdconaway/sails-ember-rest/tree/master/api/controllers/user

To delve into the specifics, you can see that this action in the user controller folder is totally custom (and could therefore be an actions2 action): https://github.com/mdconaway/sails-ember-rest/blob/master/api/controllers/user/findone.js

Whereas all of the other actions are the sails-ember-rest actions that have been imported and re-exported in place, as in: https://github.com/mdconaway/sails-ember-rest/blob/master/api/controllers/user/destroy.js

I also added 2 different ways to safely pass interrupts to the action constructors, and you can see the possibilities and variances in the following two files:
https://github.com/mdconaway/sails-ember-rest/blob/master/api/controllers/user/create.js
https://github.com/mdconaway/sails-ember-rest/blob/master/api/controllers/user/find.js

Ideally, because of the way the controller actions have already been partitioned out in this library, I should be able to slowly modernize them into actions2 actions individually.


Does this fit your need?  If so I will work on making a new generator type that will build actions2 oriented controller folders, whereas the current generator will still be left in the library to make more 'classic' controllers.

**Comment by erzzo** [comment]
Yeah, this sounds good! I'm a little busy this week but I will try it out.

The generator (I think that this can wait) could look like the one that has sails implemented:
`sails generate action user/signup --actions2`

**Comment by mdconaway** [comment]
I have documented how to use the exported actions in the README and have published the action exports via npm with sails-ember-rest@1.0.13

I will make the new generators as part of a new task when I get around to refactoring the actions themselves to be actions2 actions.

Let me know if this release works for your current needs!
